<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="6" failed="1" ignored="4" total="12" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Test-class Suite" duration-ms="159123" started-at="2020-02-02T15:14:46Z" finished-at="2020-02-02T15:17:26Z">
    <groups>
    </groups>
    <test name="Test-class test 1 Production" duration-ms="159123" started-at="2020-02-02T15:14:46Z" finished-at="2020-02-02T15:17:26Z">
      <class name="TestNG.sanityAllOptionsTest">
        <test-method status="PASS" signature="initialQuestions()[pri:10, instance:TestNG.sanityAllOptionsTest@2cf3d63b]" name="initialQuestions" duration-ms="54482" started-at="2020-02-02T15:14:46Z" finished-at="2020-02-02T15:15:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialQuestions -->
        <test-method status="FAIL" signature="initialOfferScreen()[pri:30, instance:TestNG.sanityAllOptionsTest@2cf3d63b]" name="initialOfferScreen" duration-ms="104596" started-at="2020-02-02T15:15:41Z" depends-on-methods="TestNG.sanityAllOptionsTest.initialQuestions" finished-at="2020-02-02T15:17:26Z">
          <exception class="java.lang.Exception">
            <message>
              <![CDATA[Failed in INITIAL OFFER SCREEN QUESTION]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Exception: Failed in INITIAL OFFER SCREEN QUESTION
at TestNG.sanityAllOptionsTest.initialOfferScreen(sanityAllOptionsTest.java:131)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Exception -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialOfferScreen -->
        <test-method status="SKIP" signature="finalQuestions()[pri:40, instance:TestNG.sanityAllOptionsTest@2cf3d63b]" name="finalQuestions" duration-ms="0" started-at="2020-02-02T15:17:26Z" depends-on-methods="TestNG.sanityAllOptionsTest.initialOfferScreen" finished-at="2020-02-02T15:17:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method sanityAllOptionsTest.finalQuestions()[pri:40, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method sanityAllOptionsTest.finalQuestions()[pri:40, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalQuestions -->
        <test-method status="SKIP" signature="finalOfferScreen()[pri:50, instance:TestNG.sanityAllOptionsTest@2cf3d63b]" name="finalOfferScreen" duration-ms="0" started-at="2020-02-02T15:17:26Z" depends-on-methods="TestNG.sanityAllOptionsTest.initialOfferScreen" finished-at="2020-02-02T15:17:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method sanityAllOptionsTest.finalOfferScreen()[pri:50, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method sanityAllOptionsTest.finalOfferScreen()[pri:50, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalOfferScreen -->
        <test-method status="SKIP" signature="covers()[pri:70, instance:TestNG.sanityAllOptionsTest@2cf3d63b]" name="covers" duration-ms="0" started-at="2020-02-02T15:17:26Z" depends-on-methods="TestNG.sanityAllOptionsTest.initialOfferScreen" finished-at="2020-02-02T15:17:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method sanityAllOptionsTest.covers()[pri:70, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method sanityAllOptionsTest.covers()[pri:70, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- covers -->
        <test-method status="SKIP" signature="payments()[pri:80, instance:TestNG.sanityAllOptionsTest@2cf3d63b]" name="payments" duration-ms="0" started-at="2020-02-02T15:17:26Z" depends-on-methods="TestNG.sanityAllOptionsTest.initialOfferScreen" finished-at="2020-02-02T15:17:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method sanityAllOptionsTest.payments()[pri:80, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method sanityAllOptionsTest.payments()[pri:80, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- payments -->
        <test-method status="SKIP" signature="returnSteps()[pri:85, instance:TestNG.sanityAllOptionsTest@2cf3d63b]" name="returnSteps" duration-ms="0" started-at="2020-02-02T15:17:26Z" depends-on-methods="TestNG.sanityAllOptionsTest.initialOfferScreen" finished-at="2020-02-02T15:17:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method sanityAllOptionsTest.returnSteps()[pri:85, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method sanityAllOptionsTest.returnSteps()[pri:85, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- returnSteps -->
        <test-method status="SKIP" signature="forwardSteps()[pri:86, instance:TestNG.sanityAllOptionsTest@2cf3d63b]" name="forwardSteps" duration-ms="0" started-at="2020-02-02T15:17:26Z" depends-on-methods="TestNG.sanityAllOptionsTest.initialOfferScreen" finished-at="2020-02-02T15:17:26Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method sanityAllOptionsTest.forwardSteps()[pri:86, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method sanityAllOptionsTest.forwardSteps()[pri:86, instance:TestNG.sanityAllOptionsTest@2cf3d63b] depends on not successfully finished methods
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:888)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- forwardSteps -->
      </class> <!-- TestNG.sanityAllOptionsTest -->
    </test> <!-- Test-class test 1 Production -->
  </suite> <!-- Test-class Suite -->
</testng-results>
